include ../NickelSeries/lib/nh/NickelHook.mk

override LIBRARY  := libdfh.so
override SOURCES  += dfh.cc
override CXXFLAGS += -Wall -Wextra -Werror -Wno-missing-field-initializers -Wno-deprecated-declarations

include ../NickelSeries/lib/nh/NickelHook.mk
